version: '3'

services:
  nginx:
    container_name: dishwasher-frontend
    # image: nginx:1.15-alpine
    build: .
    image: dishwasher-frontend-image
    restart: unless-stopped
    environment:
        NODE_ENV: production
    volumes:
      - ./server/nginx:/etc/nginx/conf.d
      - ./server/certbot/conf:/etc/letsencrypt
      - ./server/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: dishwasher-frontend-certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./server/certbot/conf:/etc/letsencrypt
      - ./server/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
